# Generated by Django 5.1.1 on 2024-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('sender', models.CharField(default='Guest', max_length=255)),
                ('receiver', models.CharField(default='Guest', max_length=255)),
            ],
        ),
    ]
