# Generated by Django 5.1.1 on 2024-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg',
            field=models.TextField(default=''),
        ),
    ]
