# Generated by Django 4.2.16 on 2024-10-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_msg_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='receiver',
        ),
    ]
