# Generated by Django 4.2.16 on 2024-10-16 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_msg_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='lastSent',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 3, 7, 36, 793570)),
        ),
    ]
