# Generated by Django 4.2.16 on 2024-10-17 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_msg_lastsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='lastSent',
        ),
        migrations.AddField(
            model_name='msg',
            name='senton',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 3, 3, 41, 786637)),
        ),
        migrations.AlterField(
            model_name='msg',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
