# Generated by Django 4.2.16 on 2024-10-17 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_msg_senton_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='senton',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 6, 22, 37, 115264)),
        ),
    ]
