# Generated by Django 4.2.16 on 2024-10-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_msg_sender_alter_msg_senton'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='sender',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='senton',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 10, 33, 5, 784277)),
        ),
    ]
