# Generated by Django 4.2.16 on 2024-10-17 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_msg_sender_alter_msg_senton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='user',
        ),
        migrations.AlterField(
            model_name='msg',
            name='senton',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 10, 34, 2, 137)),
        ),
    ]
